<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
	$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
?>
<?php if ($title):?>
<div class="block-title">
	<strong><?php echo $block->escapeHtml($title) ?></strong>
</div>
<?php endif ?>
<div class="block-content catalog-category">
<?php
foreach($categories as $category):
        $cat = $this->getCategoryModel($category->getId());
        ?>
        <span class="category">
        	<a href="<?php echo $block->escapeUrl($cat->getUrl()) ?>">
        		<?php if($canShowImg && $cat->getImageUrl()):?>
        			<img src="<?php echo $block->escapeUrl($cat->getImageUrl()) ?>" alt="" width="<?=$this->getImageWidth();?>" height="<?=$this->getImageHeight()?>"/>
        		<?php else:?>
        		<span class="cat-title"><?php echo $block->escapeHtml($cat->getName()) ?></span>
        		<?php endif;?>
        	</a>
        </span>
        <?php
endforeach;
?>
</div>