<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
	$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
?>
<?php if ($title):?>
<div class="block-title">
	<strong><?php echo $block->escapeHtml($title) ?></strong>
</div>
<?php endif ?>
<div class="block-content catalog-category">
<?php foreach($categories as $category):?>
        <span class="category">
        	<a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
        		<?php if($canShowImg && $category->getImageUrl()):?>
        			<img src="<?php echo $block->escapeUrl($cat->getImageUrl()) ?>" alt="" width="<?=$this->getImageWidth();?>" height="<?=$this->getImageHeight()?>"/>
        		<?php else:?>
        		<span class="cat-title"><?php echo $block->escapeHtml($category->getName()) ?></span>
        		<?php endif;?>
        	</a>
        </span>
        <?php
endforeach;
?>
</div>