<?php
$category = $block->getPreviousCategory();
?>
<?php if ($category): ?>
    <ul class="block-content catalog-category pager" aria-labelledby="paging-label">
        <li class="catalog-category-previous">
            <a class="action previous"
               href="<?= $block->escapeUrl($category->getUrl()) ?>"
               title="<?= $block->escapeHtmlAttr(__($category->getName())) ?>">
                <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                <span><?= $block->escapeHtml(__('Previous')) ?></span>
            </a>
        </li>
    </ul>
<?php endif; ?>
